name: "ReSharper"
author: DevOps
description: Run ReSharper

inputs:
  json-file: 
    description: The name of json file
    required: true
runs:
  using: "composite"
  steps:
    - name: Python 3
      uses: actions/setup-python@v1
      with: 
        python-version: 3.9
    - name: Requirements
      run: |
         pip install -r requirements.txt
      shell: bash
    - id: verify-secret-action
      env:
        INPUTS_JSON_FILE: ${{ inputs.json-file }}
      run: ${{ github.action_path }}/action.py
      shell: bash

