name: "VerifySecret"
author: DevOps
description: Run Secret Verifier

inputs:
  json-file: 
    description: The name of json file
    required: true
runs:
  using: "composite"
  steps:
    - id: verify-secret-action
      env:
        INPUTS_JSON_FILE: ${{ inputs.json-file }}
      run: |
        pip3 install --break-system-packages boto3
        python3 ${{ github.action_path }}/action.py
      shell: bash

