name: Secret-Verify-test-action
on: 
  push:
    branches:
      - "*"
      - "!main"
  workflow_dispatch:
    inputs:
      json-file:
        description: 'Json file to parse looking for the keyword: secret'
        required: true
jobs:
  test-action:
    name: Test Verify Secret
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Python 3
        uses: actions/setup-python@v1
        with: 
          python-version: 3.9
          
      - name: Run Secret Verifier
        uses: ./
        with:
          json-file: test.json
        
